name = "news-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[vars]
FIREBASE_PROJECT_ID = "ai-news-app-f24cf"
ENV = "dev"
ALLOWED_ORIGINS = "https://ai-news-app-f24cf.web.app,https://ai-news-app-f24cf.firebaseapp.com,http://localhost:5173,http://localhost:4173"

[[d1_databases]]
binding = "DB"
database_name = "news-db"
database_id = "d93210a9-d7da-4da8-9c8e-5f02df223744"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "b86063b5c21f4e1e92e101677a48eec4"

[ai]
binding = "AI"
